# Generated by Django 6.0.7 on 2026-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auditlog_latitude_auditlog_longitude_auditlog_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgtransaction',
            name='lender',
            field=models.CharField(blank=True, default='smsquare', max_length=20),
        ),
        migrations.AddField(
            model_name='portalsession',
            name='finance_lenders',
            field=models.JSONField(default=dict),
        ),
    ]
