# Generated by Django 6.0.7 on 2026-07-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_pgtransaction_lender_portalsession_finance_lenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsession',
            name='last_lender_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
