# Generated by Django 6.0.7 on 2026-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_portalsession_last_lender_scan_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgtransaction',
            name='gateway',
            field=models.CharField(default='allcloud', max_length=20),
        ),
    ]
