# Generated by Django 6.0.7 on 2026-07-24 06:19

import django.utils.timezone
import portal.models
import portal.services.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_pgtransaction_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTrust',
            fields=[
                ('id', models.CharField(default=portal.models.new_uuid, max_length=32, primary_key=True, serialize=False)),
                ('mobile', portal.services.crypto.EncryptedCharField(max_length=512)),
                ('mobile_mask', models.CharField(max_length=20)),
                ('pin_hash', models.CharField(max_length=128)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'device_trusts',
            },
        ),
    ]
