# Generated by Django 6.0.7 on 2026-07-24 07:28

import portal.models
import portal.services.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_devicetrust'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedLoan',
            fields=[
                ('id', models.CharField(default=portal.models.new_uuid, max_length=32, primary_key=True, serialize=False)),
                ('finance_id', models.CharField(db_index=True, max_length=40)),
                ('agreement_no', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('lender', models.CharField(default='smsquare', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('mobile', portal.services.crypto.EncryptedCharField(blank=True, default='', max_length=512)),
                ('mobile_mask', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=80)),
                ('centre', models.CharField(blank=True, default='', max_length=80)),
                ('rsp_name', models.CharField(blank=True, default='', max_length=80)),
                ('reason', models.TextField(blank=True, default='')),
                ('blocked_by', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocked_loans',
                'constraints': [models.UniqueConstraint(fields=('finance_id', 'lender'), name='uniq_blocked_loan')],
            },
        ),
    ]
