from django.urls import path

from portal.views import auth, dashboard, dev, geo, payments, pwa, staff, verify

urlpatterns = [
    path("", dashboard.index, name="index"),
    path("verify/<str:token>", verify.verify_document, name="verify_document"),
    path("device-location", geo.device_location, name="device_location"),
    path("sw.js", pwa.service_worker, name="service_worker"),
    path("login", auth.login_page, name="login"),
    path("login/send-otp", auth.send_otp, name="send_otp"),
    path("login/resend-otp", auth.resend_otp, name="resend_otp"),
    path("login/verify-otp", auth.verify_otp, name="verify_otp"),
    path("login/agreement", auth.agreement_dispatch, name="agreement_login"),
    path("login/pin", auth.pin_unlock, name="pin_unlock"),
    path("logout", auth.logout, name="logout"),
    path("lang/<str:code>", auth.set_lang, name="set_lang"),
    path("dashboard", dashboard.dashboard, name="dashboard"),
    path("dashboard/dismiss-pin-prompt", dashboard.dismiss_pin_prompt, name="dismiss_pin_prompt"),
    path("profile", dashboard.profile_page, name="profile"),
    path("profile/pin/setup", auth.pin_setup, name="pin_setup"),
    path("profile/pin/disable", auth.pin_disable, name="pin_disable"),
    path("loan/<str:finance_id>", dashboard.loan_detail, name="loan_detail"),
    path("loan/<str:finance_id>/pay", payments.pay_page, name="pay_page"),
    path("loan/<str:finance_id>/downloads", payments.downloads_page, name="downloads_page"),
    path("loan/<str:finance_id>/statement.pdf", payments.statement_pdf, name="statement_pdf"),
    path("loan/<str:finance_id>/statement/view", payments.statement_view, name="statement_view"),
    path("loan/<str:finance_id>/foreclosure.pdf", payments.foreclosure_statement_pdf, name="foreclosure_statement_pdf"),
    path("loan/<str:finance_id>/foreclosure/view", payments.foreclosure_view, name="foreclosure_view"),
    path("loan/<str:finance_id>/foreclosure/pay", payments.generate_foreclosure_qr, name="generate_foreclosure_qr"),
    path("loan/<str:finance_id>/pay/qr", payments.generate_qr, name="generate_qr"),
    path("loan/<str:finance_id>/pay/phonepe", payments.generate_phonepe_order, name="generate_phonepe_order"),
    path("loan/<str:finance_id>/pay/phonepe/return/<str:txn_key>",
         payments.phonepe_return, name="phonepe_return"),
    path("payment/phonepe/webhook", payments.phonepe_webhook, name="phonepe_webhook"),
    path("payment/<int:txn_id>/receipt.pdf", payments.receipt_pdf, name="receipt_pdf"),
    path("payment/<int:txn_id>/receipt/view", payments.payment_receipt_view, name="payment_receipt_view"),
    path("loan/<str:finance_id>/receipt/<str:target_date>.pdf",
         payments.receipt_by_date_pdf, name="receipt_by_date_pdf"),
    path("loan/<str:finance_id>/receipt/<str:target_date>/view",
         payments.receipt_by_date_view, name="receipt_by_date_view"),
    path("loan/<str:finance_id>/charges/<str:target_date>/receipt.pdf",
         payments.charge_receipt_pdf, name="charge_receipt_pdf"),
    path("loan/<str:finance_id>/charges/<str:target_date>/receipt/view",
         payments.charge_receipt_view, name="charge_receipt_view"),
    path("dev/lms-probe", dev.lms_probe, name="lms_probe"),
    path("staff/login", staff.login_dispatch, name="staff_login"),
    path("staff/logout", staff.logout, name="staff_logout"),
    path("staff/report", staff.report, name="staff_report"),
    path("staff/report/export", staff.export, name="staff_report_export"),
    path("staff/blocked-loans", staff.blocked_loans_list, name="blocked_loans_list"),
    path("staff/blocked-loans/add", staff.blocked_loan_add_page, name="blocked_loan_add_page"),
    path("staff/blocked-loans/lookup", staff.blocked_loan_lookup, name="blocked_loan_lookup"),
    path("staff/blocked-loans/create", staff.blocked_loan_create, name="blocked_loan_create"),
    path("staff/blocked-loans/remove", staff.blocked_loan_remove, name="blocked_loan_remove"),
    path("staff/blocked-loans/export", staff.blocked_loans_export, name="blocked_loans_export"),
    path("staff/blocked-loans/upload", staff.blocked_loans_upload, name="blocked_loans_upload"),
    path("staff/blocked-loans/sample", staff.blocked_loans_sample, name="blocked_loans_sample"),
]
